repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: '(?:.*[\\/])?\.bumpversion\.cfg$'
      - id: trailing-whitespace
        exclude: '(?:.*[\\/])?\.bumpversion\.cfg$'
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
